{'batch_size': 16, 'x_dim': 784, 'hidden_dim': 400, 'latent_dim': 20, 'lr': 0.001, 'epochs': 10}
Start training VAE...
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
Traceback (most recent call last):
  File "/Users/tinghui/workspace/github/DTU02476-Machine-Learning-Operations/s4_debugging_and_logging/sweep_exercise/train.py", line 181, in <module>
    train(config_defaults)
  File "/Users/tinghui/workspace/github/DTU02476-Machine-Learning-Operations/s4_debugging_and_logging/sweep_exercise/train.py", line 148, in train
    wandb.log({"val_loss": validation_loss})
                           ^^^^^^^^^^^^^^^
NameError: name 'validation_loss' is not defined
3600
3700
	Epoch 1 complete! 	Average Loss:  129.4819460746987